"""What may be deleted, what is in use, and permanent deletion."""
from __future__ import annotations

import os
import stat
import subprocess

import psutil

from cleaner.scan import nc, under

LINK_TAGS = {0xA0000003, 0xA000000C}  # junction, symlink
DIRECTORY = 0x10
ENV = os.environ
SYSTEM_ROOT = nc(ENV.get("SystemRoot", r"C:\Windows"))
PROGRAM_DATA = nc(ENV.get("ProgramData", r"C:\ProgramData"))

# Folders whose *contents* are regenerated by Windows and safe to clear, even though
# they live inside otherwise protected places.
CLEARABLE_SYSTEM = [
    nc(os.path.join(SYSTEM_ROOT, p)) for p in (
        "Temp", "Minidump", "LiveKernelReports", r"SoftwareDistribution\Download", r"Logs\CBS",
        r"ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Cache",
    )
] + [nc(os.path.join(PROGRAM_DATA, r"Microsoft\Windows\WER", p)) for p in ("ReportArchive", "ReportQueue")]
CLEARABLE_FILES = {nc(os.path.join(SYSTEM_ROOT, "MEMORY.DMP"))}

# Relative to any drive root: never touch anything inside these.
PROTECTED_TREES = {
    "windows", "system volume information", "$recycle.bin", "recovery", "boot", "efi", "config.msi",
    r"program files\windowsapps", r"program files\common files", r"program files (x86)\common files",
    r"programdata\microsoft",
}
# Relative to any drive root: the folder itself must stay, its contents may go.
PROTECTED_EXACT = {
    "", "program files", "program files (x86)", "programdata", "users", r"users\public", r"users\default",
    "pagefile.sys", "hiberfil.sys", "swapfile.sys", "bootmgr",
}
USER_FOLDERS = {
    "appdata", "desktop", "documents", "downloads", "pictures", "music", "videos", "favorites",
    "contacts", "links", "saved games", "searches", "3d objects",
}
APP_HOME = nc(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def protected_reason(path: str) -> str | None:
    p = nc(path)
    if p in CLEARABLE_FILES or any(p != c and under(p, c) for c in CLEARABLE_SYSTEM):
        return None
    rest = os.path.splitdrive(p)[1].strip("\\")
    if rest in PROTECTED_EXACT:
        return "Required by Windows"
    parts = rest.split("\\")
    for tree in PROTECTED_TREES:
        if under(rest, tree):
            return "Windows system files"
    if parts[0] == "users" and (
        len(parts) == 2
        or (len(parts) == 3 and (parts[2] in USER_FOLDERS or parts[2].startswith("onedrive")))
        or (len(parts) == 4 and parts[2] == "appdata")
    ):
        return "Main user folder (its contents can be cleaned)"
    if os.path.basename(p).startswith(("ntuser.", "usrclass.dat")):
        return "Your Windows user settings"
    if under(APP_HOME, p) or under(p, APP_HOME):
        return "DriveSweep itself"
    return None


def onedrive_roots() -> list[str]:
    return [nc(ENV[k]) for k in ("OneDrive", "OneDriveConsumer", "OneDriveCommercial") if ENV.get(k)]


def running_programs() -> list[tuple[str, str]]:
    """(process name, normcased exe path) for every process we can see."""
    out = []
    for proc in psutil.process_iter(["name", "exe"]):
        exe = proc.info.get("exe")
        if exe and os.path.isabs(exe):  # system processes like "Registry" report a bare name
            out.append((proc.info["name"], nc(exe)))
    return out


def used_by(path: str, programs: list[tuple[str, str]]) -> list[str]:
    p = nc(path)
    return sorted({name for name, exe in programs if under(exe, p)})


class Progress:
    def __init__(self) -> None:
        self.freed = 0
        self.files = 0
        self.current = ""
        self.skipped: list[tuple[str, str]] = []  # (path, reason), first 300 only
        self.skipped_count = 0
        # moves: "copying" then "removing" the originals (their deletion is tracked in `cleanup`)
        self.stage = ""
        self.removed = 0
        self.cleanup: Progress | None = None

    def skip(self, path: str, reason: str) -> None:
        self.skipped_count += 1
        if len(self.skipped) < 300:
            self.skipped.append((path, reason))


def delete_path(path: str, progress: Progress, contents_only: bool = False) -> int:
    """Permanently delete a file/folder (or only a folder's contents). Returns bytes freed."""
    before = progress.freed
    if contents_only:
        try:
            with os.scandir(path) as it:
                children = [e.path for e in it]
        except FileNotFoundError:
            return 0
        except OSError as error:
            progress.skip(path, _why(error))
            return 0
        for child in children:
            delete_path(child, progress)
        return progress.freed - before
    reason = protected_reason(path)
    if reason:
        progress.skip(path, reason)
        return 0
    _remove(path, progress)
    return progress.freed - before


def _remove(path: str, progress: Progress) -> None:
    try:
        st = os.lstat(path)
    except FileNotFoundError:
        return
    except OSError as error:
        progress.skip(path, _why(error))
        return
    attrs = st.st_file_attributes
    is_dir = bool(attrs & DIRECTORY)
    progress.current = path
    if st.st_reparse_tag in LINK_TAGS:  # remove the link only, never what it points to
        _try(os.rmdir if is_dir else os.unlink, path, progress)
        return
    if is_dir:
        try:
            with os.scandir(path) as it:
                children = [e.path for e in it]
        except OSError as error:
            progress.skip(path, _why(error))
            return
        for child in children:
            _remove(child, progress)
        try:
            os.rmdir(path)
        except OSError:
            pass  # not empty: the files that stayed were already reported
        return
    if _try(os.unlink, path, progress):
        progress.freed += st.st_size
        progress.files += 1


def _try(fn, path: str, progress: Progress) -> bool:
    try:
        fn(path)
        return True
    except FileNotFoundError:
        return False
    except PermissionError:
        try:  # read-only attribute blocks deletion on Windows
            os.chmod(path, stat.S_IWRITE)
            fn(path)
            return True
        except OSError as error:
            progress.skip(path, _why(error))
    except OSError as error:
        progress.skip(path, _why(error))
    return False


def _why(error: OSError) -> str:
    if getattr(error, "winerror", None) == 32:
        return "In use by another program"
    if isinstance(error, PermissionError):
        return "Access denied (in use or needs admin)"
    return error.strerror or str(error)


def take_ownership(path: str) -> None:
    """Old Windows installs are owned by TrustedInstaller; admins must take ownership first."""
    flags = subprocess.CREATE_NO_WINDOW
    subprocess.run(["takeown", "/F", path, "/R", "/A", "/D", "Y"], capture_output=True, creationflags=flags)
    subprocess.run(["icacls", path, "/grant", "*S-1-5-32-544:F", "/T", "/C", "/Q"], capture_output=True, creationflags=flags)
